services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/calticpe-docker
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
