name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports: [27017:27017]

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    - name: Crear archivo .env
      run: |
        echo "MONGO_URI=mongodb://localhost:27017/calticpe-test" > .env
        echo "NODE_ENV=test" >> .env

    - name: Ejecutar pruebas
      run: npm test
